# Generated by Django 5.1.1 on 2024-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('flight', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('planned_date', models.DateField()),
                ('planned_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
