# Generated by Django 5.1.1 on 2024-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storybanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
